### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by yohandalpe** [vinitkumar/node-twitter#199]
Hi, I am unable to run the program. I am getting this error.
OS: Ubuntu 16.04 x64 with MEAN Stack.
Used command:  node server.js

node-twitter/app/models/tweets.js:99
    let index = utils.indexof(this.comments, { id: commentId });
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /opt/proof.id/node-twitter/server.js:20:3
    at Array.forEach (native)
    at Object.<anonymous> (/opt/proof.id/node-twitter/server.js:19:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18) 

Thanks.

**Comment by vinitkumar** [comment]
@yohandalpe Hi, Thanks for reporting the issue. At the first glance, the issue looks like that you are running an old version of node.js. A good way to find out is to run this command:

```
~ ➤ node --version
v8.7.0
```
Please check what is the value you get and report it back.

One sure shot way to get this done is to go to the node.js website(node.js)[https://nodejs.org/en/] and download the one for Ubuntu.

**Comment by yohandalpe** [comment]
Hi, Thank you for your reply. I updated my node version. Now I am getting this error.

raven@2.2.1 alert: no DSN provided, error reporting disabled
Express app started on port 3000
Error: listen EADDRINUSE :::3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1354:14)
    at listenInCluster (net.js:1395:12)
    at Server.listen (net.js:1479:7)
    at Function.listen (/opt/proof.id/node-twitter/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/opt/proof.id/node-twitter/server.js:27:5)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Note: I am new to NodeJS.

**Comment by vinitkumar** [comment]
Hi. Let's try and understand what this error means:

`Error: listen EADDRINUSE :::3000`. This means that the server is supposed to run on port `:3000` but is not able to do so since there is already something else running on that port.

Now, there are two options, 

- Easy way 

Run:

```
export PORT='3001'
node server.js
```
This will change the server's port to 3001 and the site would be running on `http://localhost:3001`.

- Hard Way

Either close what is running on that port by running

```
ps
8437 ttys001    0:00.74 -zsh
8467 ttys001    0:00.44 node server.js
16727 ttys001    0:01.85 /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -W0 /usr/local/Homebrew/Library/Homebrew/brew.rb upgrade vim macvim git
```

Kill this process using `kill -9 8467`.

**Comment by yohandalpe** [comment]
Hi, It works now. Thanks a bunch for your help. :)

**Comment by vinitkumar** [comment]
Great! Glad to help.
