### ISSUE TITLE
Unable to run application 

### ISSUE THREAD

**Issue by MiguelMazariegos** [vinitkumar/node-twitter#243]
Error: secret option required for sessions
    at session (C:\xampp\htdocs\node-twitter-master\node_modules\express-session\index.js:199:12)
    at Layer.handle [as handle_request] (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:317:13)
    at C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:275:10)
    at methodOverride (C:\xampp\htdocs\node-twitter-master\node_modules\method-override\index.js:65:14)
    at Layer.handle [as handle_request] (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:317:13)
    at C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\xampp\htdocs\node-twitter-master\node_modules\body-parser\lib\types\json.js:110:7)
    at Layer.handle [as handle_request] (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:317:13)
    at C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\xampp\htdocs\node-twitter-master\node_modules\body-parser\lib\types\urlencoded.js:91:7)
    at Layer.handle [as handle_request] (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:317:13)
    at C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:275:10)
    at cookieParser (C:\xampp\htdocs\node-twitter-master\node_modules\cookie-parser\index.js:57:14)
    at Layer.handle [as handle_request] (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:317:13)
    at C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:275:10)
    at C:\xampp\htdocs\node-twitter-master\node_modules\view-helpers\index.js:68:5
    at Layer.handle [as handle_request] (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:317:13)
    at C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\express\lib\router\index.js:275:10)
    at SendStream.error (C:\xampp\htdocs\node-twitter-master\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (events.js:189:13)
    at SendStream.EventEmitter.emit (domain.js:441:20)
    at SendStream.error (C:\xampp\htdocs\node-twitter-master\node_modules\send\index.js:270:17)
    at SendStream.onStatError (C:\xampp\htdocs\node-twitter-master\node_modules\send\index.js:421:12)
    at next (C:\xampp\htdocs\node-twitter-master\node_modules\send\index.js:736:16)
    at onstat (C:\xampp\htdocs\node-twitter-master\node_modules\send\index.js:725:14)
    at FSReqWrap.oncomplete (fs.js:154:21)

**Comment by vinitkumar** [comment]
Hi @MiguelMazariegos you need to add this environment variable https://github.com/vinitkumar/node-twitter/blob/master/config/config.js#L5

**Comment by MiguelMazariegos** [comment]
Hi @vinitkumar, It seems that the variable is there. Is there another reason why this problem might be happening?

**Comment by vinitkumar** [comment]
your error says it is not defined. Could you please check again?

**Comment by MiguelMazariegos** [comment]
Well this is my config.js file
const path = require("path");
const rootPath = path.normalize(__dirname + "/..");
const DB = process.env.DB;
const clientID = process.env.GITHUB_CLIENT_ID;
const clientSecret = process.env.GITHUB_CLIENT_SECRET;

module.exports = {
  development: {
    db: "mongodb://localhost:27017/ntwitter",
    root: rootPath,
    app: {
      name: "Node Twitter"
    },
    github: {
      clientID: "c80478ae18ead326a4bf",
      clientSecret: "480ad67b6c90d02c47da69aa941b9e6e4a1a93fd",
      callbackURL: "http://localhost:3000/auth/github/callback"
    }
  },
  test: {
    db: "mongodb://root:volvo76@ds039078.mongolab.com:39078/ntwitter",
    root: rootPath,
    app: {
      name: "Nodejs Express Mongoose Demo"
    },
    github: {
      clientID: "c2e0f478634366e1289d",
      clientSecret: "0bfde82383deeb99b28d0f6a9eac001a0deb798a",
      callbackURL: "http://localhost:3000/auth/github/callback"
    }
  },
  production: {
    db: DB,
    root: rootPath,
    app: {
      name: "Nodejs Express Mongoose Demo"
    },
    github: {
      clientID: clientID,
      clientSecret: clientSecret,
      callbackURL: "http://nitter.herokuapp.com/auth/github/callback"
    }
  }
};

**Comment by vinitkumar** [comment]
@MiguelMazariegos I think you missed my point. The variable is sure defined but if you look closely, it is `process.env.GITHUB_CLIENT_SECRET`. That means you need to define those in environment variables, if it is not set then it won't work.

You can set it like this

`export GITHUB_CLIENT_SECRET='nhadhadjajdjadjadjajdjadj'`
Where `nhadhadjajdjadjadjajdjadj` is the value you get from github application settings. Please refer the readme again.

**Comment by MiguelMazariegos** [comment]
That was the issue.
It is working now, thanks for the help.

**Comment by vinitkumar** [comment]
@MiguelMazariegos cool, glad to be of help.
